1: Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.

In [2]:
import numpy as np
import pandas as pd

In [3]:

def Vandermonde(arr,n, increase = False):
    if increase:
        final_mat = np.array([i**j for i in arr for j in range(n)]).reshape(arr.size,n)
    elif not increase:
        final_mat = np.array([i**(n-j-1) for i in arr for j in range(n)]).reshape(arr.size,n)
        
    return final_mat

In [4]:
arr = np.array([1,2,3,4,5])
n = 3
Vandermonde(arr,n,True)     #increasing not False

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])

In [5]:
arr = np.array([1,2,3,4,5])
n = 3
Vandermonde(arr,n,False)  #increasing False

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

2: Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10 ===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100 y1 25 = (10+20+30+40)/4 y2 35 = (20+30+40+50)/4 y3 45 = (30+40+50+60)/4 y4 55 = (40+50+60+70)/4 y5 65 = (50+60+70+80)/4 y6 75 = (60+70+80+90)/4 y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
def Moving_Avg(a,w):
    seq = a.size-w+1
    mat = np.array([arr2[i+j] for i in range(seq) for j in range(w)]).reshape(seq,w)
    res = np.sum(mat,axis = 1,keepdims=True)/w
    for x,y in zip(mat,res):
        print(x,y)

In [7]:
arr2 = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
w = 3

In [8]:
Moving_Avg(arr2,w)

[3 5 7] [5.]
[5 7 2] [4.66666667]
[7 2 8] [5.66666667]
[ 2  8 10] [6.66666667]
[ 8 10 11] [9.66666667]
[10 11 65] [28.66666667]
[11 65 72] [49.33333333]
[65 72 81] [72.66666667]
[72 81 99] [84.]
[ 81  99 100] [93.33333333]
[ 99 100 150] [116.33333333]
